### PR TITLE
Added JPQL console

### PR DESCRIPTION
**Pull request by IvanMalofeev**

### CODE REVIEW

**Comment by mariodavid** [comment]
Hi Ivan,

thanks for the pull request. I will go through the code and try it myself. It seems like a very valuable feature.

Could you in the meantime add some more tests so that the coverage rate is high enough? That would be great. You can also add additional tests to the project if you want to do me a favor and raise the bar for the coverage.

**Comment by mariodavid** [comment]
I tried to execute it. It seems to work fine.

But I found an error, that would be great if you can take a look at.

When entering an invalid JPQL like: "select e from sec$User" instead of "select e from sec$User e", there is a NullPointerException in SqlDiagnoseServiceBean:73, because

````
sqlSelectResult = executeJpqlStatement(queryStatement)
diagnoseExecution = createAdHocDiagnose(queryStatement, DiagnoseType.JPQL)
````

`diagnoseExecution` is not initialized since `executeJpqlStatement` throws already the exception (JpqlSyntaxException). This might simply be resolved by creating the diagnoseExecution before calling `executeJpqlStatement`, so basically switching these two lines.

I think it is totally ok to prompt the user with the raw exception (JpqlSyntaxException in this case) that states that there is a problem with the SQL / JPQL statement (just like if you enter "hello world" will prompt the user a ParseException)

Perhaps you can take a look at it (also worth a unit test).

**Comment by IvanMalofeev** [comment]
Hi.

> Could you in the meantime add some more tests so that the coverage rate is high enough?

Yes of course, right after fix this error

> But I found an error, that would be great if you can take a look at.
When entering an invalid JPQL like: "select e from sec$User" instead of "select e from sec$User e", there is a NullPointerException in SqlDiagnoseServiceBean:73

**Comment by mariodavid** [comment]
Hi,

was it by intention that you removed the web-menu.xml and the message.properties file? If this was the case - why?

**Comment by IvanMalofeev** [comment]
Hi,
No It is mistake.

**Comment by mariodavid** [comment]
Hi,

before merging I found two additional problems. 

The first one is that using a wrong error like "select e from sec$User" will lead to a empty result list. But there is no possiblity to find out what is wrong with the query. See this example:

invalid-jpql-does-not-show-error

When people want to use it as a JPQL tester (like [in this support topic](https://www.cuba-platform.com/discuss/t/jpql-tester-in-studio/2939)), this is problematic. Additionally, the user might mix up the fact that the query is corrupt with the fact that there is no result with this query.

The second problem is that collection attributes are displayed as "Indirect set: not instantiated" (see below):
error-indirect-set

I would rather just remove this attributes from the resulting table, because otherwise those would have to be fetched as well.

Perhaps there is another problem with transient properties (haven't tried it). 

When these issues are resolved, I'd love to merge it and release a version (actually two. 0.3.0 for CUBA 6.6.x with the feature and 0.4.0 for CUBA 6.7.x).

**Comment by ikuchmin** [comment]
Hi, Mario

We have resolved issues. Collection attributes are not shown and we have added "true" JPQL parser for the JPQL Console. I think that the pull request is ready being merged to master.

**Comment by mariodavid** [comment]
Hi,

I took a look at it. Everything seems to be fine. Thanks for your contribution - will merge it.

**Pull request merged**
