### PR TITLE
Jpql to sql

### PR DESCRIPTION
**Pull request by slogan163**
I add ability convert jpql to sql (button 'generate to sql', which open dialog with text editor). This sql can be copied to clipboard.

### CODE REVIEW

**Comment by ikuchmin** [comment]
Hello. What do you think about pull request?

**Comment by mariodavid** [comment]
hi, thanks for the contribution. I hadn't time to look into it. Perhaps i can do it today.

**Comment by ikuchmin** [comment]
hi, would you mind to merge pull request and publish new version of component. We really need in this. Thank...

**Comment by mariodavid** [comment]
hi, sure - sorry for the delay. I looked at it manually, seems good Will merge it tonight!

**Comment by ikuchmin** [comment]
hi, I think that sql-copy-dialog window should have button with name "Close" insteading "Cancel". Please apply my patch

```diff
Index: modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/SqlCopyDialog.groovy
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/SqlCopyDialog.groovy	(date 1513693586000)
+++ modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/SqlCopyDialog.groovy	(revision )
@@ -11,10 +11,9 @@
 
     @Named('sqlTextArea')
     TextArea textArea
+
     @Named('copyBtn')
     Button copyBtn
-    @Named('cancelBtn')
-    Button cancelBtn
 
     String copyButtonClass = 'copy-sql-button'
     String sqlTextContentClass = "sql-text-content-${UUID.randomUUID()}"
@@ -28,7 +27,7 @@
         executeJs()
     }
 
-    void onCancelBtnClick() {
+    void onCloseBtnClick() {
         close('closeSqlDialog')
     }
 
Index: modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/messages.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/messages.properties	(date 1513693586000)
+++ modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/messages.properties	(revision )
@@ -2,6 +2,6 @@
 caption = JPQL-Console
 generateSql = Generate SQL
 copy=Copy
-cancel=Cancel
+close=Close
 sqlDialogHeader=SQL generated query
 wrongScript = JPQL script is not correct
Index: modules/web/test/de/diedavids/cuba/runtimediagnose/web/screens/jpql/SqlCopyDialogSpec.groovy
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modules/web/test/de/diedavids/cuba/runtimediagnose/web/screens/jpql/SqlCopyDialogSpec.groovy	(date 1513693586000)
+++ modules/web/test/de/diedavids/cuba/runtimediagnose/web/screens/jpql/SqlCopyDialogSpec.groovy	(revision )
@@ -46,7 +46,7 @@
         }
 
         when:
-        dialog.onCancelBtnClick()
+        dialog.onCloseBtnClick()
 
         then:
         countCloseWindow == 1
Index: modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/sql-copy-dialog.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/sql-copy-dialog.xml	(date 1513693586000)
+++ modules/web/src/de/diedavids/cuba/runtimediagnose/web/screens/jpql/sql-copy-dialog.xml	(revision )
@@ -12,10 +12,10 @@
             <button id="copyBtn"
                     align="MIDDLE_LEFT"
                     caption="msg://copy"/>
-            <button id="cancelBtn"
+            <button id="closeBtn"
                     align="MIDDLE_RIGHT"
-                    caption="msg://cancel"
-                    invoke="onCancelBtnClick"/>
+                    caption="msg://close"
+                    invoke="onCloseBtnClick"/>
         </buttonsPanel>
     </layout>
 </window>
```

**Comment by mariodavid** [comment]
merged and released:

https://github.com/mariodavid/cuba-component-runtime-diagnose/releases/tag/0.4.1

Thanks for contribution!

**Comment by slogan163** [comment]
Why was deleted copy button? This button exist in an error dialog. Example error_dialog

**Comment by mariodavid** [comment]
I didn't deleted it. I only deleted the cancel button since it is basically "close". And close is already there with "ESC" and the "X" on the upper right. This is just like in the "system-information" dialog of the platform.

I'm not sure what you want to show me with the screenshot. Can you elaborate a little bit?

**Comment by mariodavid** [comment]
sql-copy-dialog

**Pull request merged**
